<?php if (!defined('BASEPATH'))
    exit('No direct script access allowed');
/*
<!-- .................................. -->
<!-- ...........COPYRIGHT ............. -->
<!-- Authors : Hisyam Husein .......... -->
<!-- Email : hisyam.husein@gmail.com .. -->
<!-- About : hisyambsa.github.io ...... -->
<!-- Instagram : @hisyambsa............ -->
<!-- .................................. -->
*/
class Gcrud_model extends CI_Model
{

    public $table = 't_ppdb';
    public $id = 'id';
    public $delete_at = 'delete_at';

    function __construct()
    {
        parent::__construct();
    }
    function generateSerialNo()
    {
        if ($this->session->userdata('lastSerial') == '') {
            $this->session->set_userdata('lastSerial', 0);
            $this->session->set_userdata('lastPage', 1);
            $lastSerial = 0;
        } else {
            $lastSerial = $this->session->userdata('lastSerial');
        }
        $lastSerial++;
        $page = $this->input->post('page');
        if ($page != '') {
            $this->session->set_userdata('lastPage', $page);
        } else {
            $this->session->set_userdata('lastPage', 1);
        }
        $this->session->set_userdata('lastSerial', $lastSerial);

        return $lastSerial;
    }
}

/* End of file Gcrud_model.php */
/* Location: ./application/models/Gcrud_model.php */
/* Please DO NOT modify this information : */
/* Generated by Hisyam 2023-01-21 13:34:42 */
/* http://hisyambsa.github.io */